QuizWebsite/QuizWebsite/QuizWebsite/Pages/Cijfer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class CijferModel : PageModel
    {
        public List<Quiz> Quizlijst { get; set; }
        public decimal cijfer { get; set; }
        public int quizID { get; set; }
        public int accountID { get; set; }
        public void OnGet()
        {
            var cijferStr = Request.Query["cijfer"];
            decimal cijferInt;
            if (decimal.TryParse(cijferStr, NumberStyles.Any, CultureInfo.InvariantCulture, out cijferInt))
            {
                cijfer = cijferInt;
            }
            var quizIDStr = Request.Query["quizID"];
            if (Int32.TryParse(quizIDStr, out int quizIDInt))
            {
                Quizlijst = QuizRepository.GetQuizNaam(quizIDInt);
                quizID = quizIDInt;
            }
            var accountIDStr = Request.Query["accountID"];
            if (Int32.TryParse(accountIDStr, out int accountIDInt))
            {
                accountID = accountIDInt;
            }
            if (ModelState.IsValid)
            { 
            QuizRepository.CijferOpslaan(cijfer, quizID, accountID);
            }

        }
    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Index1.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class Index1Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/QuizJoinen.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class QuizJoinenModel : PageModel
    {
        public int accountID
        {
            get
            {
                string AccountIDStr = HttpContext.Session.GetString("accountID");
                if (AccountIDStr != null)
                {
                    int accountID = Convert.ToInt32(AccountIDStr);
                    return accountID;
                }
                else
                {
                    return -1;
                }
            }

        }
        public IActionResult OnGet([FromForm] int quizID)
        {
            if (accountID == -1)
            {
                return Redirect("/Error");
            }
            return Page();
        }
        public IActionResult OnPostJoinQuiz([FromForm] int quizID)
        {
            if (QuizRepository.QuizJoinControle(quizID))
            {
                return RedirectToPage("/VraagBeantwoorden", new { quizID = quizID, accountID = accountID });
            }
            return RedirectToPage("/homelogin");
        }
    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/QuizUpdaten.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class QuizUpdatenModel : PageModel
    {
        public int accountID
        {
            get
            {
                string AccountIDStr = HttpContext.Session.GetString("accountID");
                if (AccountIDStr != null)
                {
                    int accountID = Convert.ToInt32(AccountIDStr);
                    return accountID;
                }
                else
                {
                    return -1;
                }
            }

        }
        public int Beheerder
        {
            get
            {
                string beheerderIDStr = HttpContext.Session.GetString("beheerder");
                if (beheerderIDStr != null)
                {
                    int beheerderID = Convert.ToInt32(beheerderIDStr);
                    return beheerderID;
                }
                else
                {
                    return -1;
                }
            }

        }
        public List<Quiz> quizes = new List<Quiz>();

        public IActionResult OnGet()
        {
            if (accountID == -1)
            {
                return Redirect("/Error");
            }
            quizes = QuizRepository.GetQuizAccount(accountID);
            if (Beheerder == -1)
            {
                return Redirect("/Error");
            }
            return Page();
        }
        public IActionResult OnPostKiesQuiz([FromForm] int quizID)
        {
            if (QuizRepository.QuizControlleren(quizID, accountID))
            {
                return RedirectToPagePermanent("/Vraagaanmaken", new { quizID = quizID });
            }
            return RedirectToPage("/homelogin");
        }
    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Quizmaken.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class QuizmakenModel : PageModel
    {
        public int accountID
        {
            get
            {
                string AccountIDStr = HttpContext.Session.GetString("accountID");
                if (AccountIDStr != null)
                {
                    int accountID = Convert.ToInt32(AccountIDStr);
                    return accountID;
                }
                else
                {
                    return -1;
                }
            }

        }
        public int Beheerder
        {
            get
            {
                string beheerderIDStr = HttpContext.Session.GetString("beheerder");
                if (beheerderIDStr != null)
                {
                    int beheerderID = Convert.ToInt32(beheerderIDStr);
                    return beheerderID;
                }
                else
                {
                    return -1;
                }
            }

        }
        public IActionResult OnGet()
        {
            if (accountID == -1)
            {
                return Redirect("/Error");
            }
            if (Beheerder == -1)
            {
                return Redirect("/Error");
            }
            return Page();
        }

        public IActionResult OnPostQuizAanmaken([FromForm]string naam)
        {
            if (ModelState.IsValid)
            {
                var idquiz = QuizRepository.QuizAanmaken(naam,accountID);
                //return this.RedirectToAction
                   // ("quizID", new { quizID = "queryStringValue1" });
                //return RedirectToPage($"/Vraagaanmaken", new { idquiz = idquiz });
                return RedirectToPage ("/VraagAanmaken", new { quizID = idquiz, accountID = accountID });
            }
            else
            {
                return Page();
            }
        }
    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/VraagBeantwoorden.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class VraagBeantwoordenModel : PageModel
    {
        public List<QuizVragen> vragenlijst { get; set; }
        public List<QRYQuizVragen> vragenmetantwoord { get; set; }

        public int quizID;
        public int accountID
        {
            get
            {
                string AccountIDStr = HttpContext.Session.GetString("accountID");
                if (AccountIDStr != null)
                {
                    int accountID = Convert.ToInt32(AccountIDStr);
                    return accountID;
                }
                else
                {
                    return -1;
                }
            }

        }

        public IActionResult OnGet()
        {
            if (accountID == -1)
            {
                return Redirect("/Error");
            }
            
            var quizIDStr = Request.Query["quizID"];

            if ((this.quizID = GetCurrentQuiz(quizIDStr)) != -1)
            {
                if (quizIDStr != "" && quizIDStr != "0")
                {
                    vragenlijst = QuizRepository.QuizVragen(this.quizID);
                    vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(this.quizID);
                    return base.Page();
                }
                else
                {
                    return Redirect("/Error");
                }

            }
            else
            {
                return Redirect("/Error");
            }

        }
        public int GetCurrentQuiz(string quizIDStr)
        {
            if (Int32.TryParse(quizIDStr, out int quizid))
            {
                return quizid;
            }
            return -1;
        }

        public IActionResult OnPostQuizInleveren(int accountID, [FromForm] IEnumerable<string> vraagID, [FromForm] IEnumerable<string> antwoordID, int quizID)
        {
            int i = 0;
            int vraagInt = 0;
            int goed = 0;
            foreach (var antwoord in antwoordID)
            {
                QuizRepository.VraagBeantwoorden(accountID, Convert.ToInt32(vraagID.ElementAt(i)), Convert.ToInt32(antwoord));
                if (QuizRepository.VraagControlleren(accountID, Convert.ToInt32(vraagID.ElementAt(i)), Convert.ToInt32(antwoord)))
                {
                    goed++;
                }
                i++;
            }
            foreach (var vraag in vraagID)
            {
                vraagInt++;

            }
            //double cijfer = ((goed / vraagInt) * 100) * 0.1;
            double cijfer = (double)goed / vraagInt *100 *0.1;
            cijfer = Math.Round(cijfer, 1, MidpointRounding.ToEven);
            return RedirectToPage("/Cijfer", new { cijfer = cijfer, quizID= quizID, accountID = accountID });
        }

    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Vraagaanmaken.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class VraagaanmakenModel : PageModel
    {

        //public List<Quiz> quizid { get { return QuizRepository.GetQuiz(); } }
        public List<QuizVragen> vragenlijst { get; set; }
        public List<QRYQuizVragen> vragenmetantwoord { get; set; }
        public int quizIDInt;
        public IActionResult OnGet([FromQuery] string quizID)
        {
            
            if ((quizIDInt = GetCurrentQuiz(quizID)) != -1)
            {
                if (quizID != null && quizID != "0")
                {
                    vragenlijst = QuizRepository.QuizVragen(quizIDInt);
                    vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(quizIDInt);
                    return Page();
                }
                else
                {
                    return Redirect("/Error");
                }
                
            }
            else 
            {
                vragenlijst = QuizRepository.QuizVragen(quizIDInt);
                vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(quizIDInt);
                return Page();
            }

        }
        public int GetCurrentQuiz(string quizIDStr)
        {
            if (Int32.TryParse(quizIDStr, out int quizid))
            {
                return quizid;
            }
            return -1;
        }
        public IActionResult OnPostVraagAanmaken(string vraag, int quizIDInt)
        {
            if (ModelState.IsValid)
            {
                QuizRepository.VraagAanmaken(vraag, quizIDInt);
                vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(quizIDInt);
                return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
            }
            else 
            {
                return Redirect("/Error");
            }
        }
        public IActionResult OnPostVraagVerwijderen(int vraagID, int quizIDInt)
        {
            if (ModelState.IsValid)
            {
                QuizRepository.VraagVerwijderen(vraagID);
                vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(quizIDInt);
                return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
            }
            return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
        }
        public IActionResult OnPostAntwoordToevoegen(string antwoord, int huidigevraag, int quizIDInt)
        {
            if (ModelState.IsValid)
            {
                QuizRepository.AntwoordToevoegen(antwoord, huidigevraag);
                vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(quizIDInt);
                return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
            }
            return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
        }
        public IActionResult OnPostUpdateAntwoord(int antwoordID, int ischecked, int quizIDInt)
        {
            if (ModelState.IsValid)
            {
                bool is_checked = (ischecked == antwoordID);
               //bool is_checked = (ischecked == "on");
                QuizRepository.UpdateAntwoord(antwoordID, is_checked);
                vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(quizIDInt);
                return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
            }
            return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
        }
        public IActionResult OnPostAntwoordVerwijderen(int antwoordID, int quizIDInt)
        {
            if (ModelState.IsValid)
            {
                QuizRepository.AntwoordVerwijderen(antwoordID);
                vragenmetantwoord = QuizRepository.GetVraagMetAntwoorden(quizIDInt);
                return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
            }
            return RedirectToPage("/VraagAanmaken", new { quizID = quizIDInt });
        }

    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/loginpage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class loginpageModel : PageModel
    {
        public int accountID { get; set; }
        public bool Invalidlogin { get; private set; }

        public void OnGet()
        {
            //Hierdoor removed hij automatisch het id elke keer dat je inlogt. Zo kan je gewoon een button hebben 
            //die naar een andere pagina defineert
            HttpContext.Session.Remove("accountID");
            HttpContext.Session.Remove("PersoonID");
            HttpContext.Session.Remove("gebruiker");
            HttpContext.Session.Remove("beheerder");
        }

        public IActionResult OnPostChecklogin(string gebruikersnaam, string wachtwoord)
        {
            var checklogin = loginRepository.AccountCheck(gebruikersnaam, wachtwoord);
            if (checklogin == null)
            {
                Invalidlogin = true;
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("accountID", checklogin.accountID.ToString());
                HttpContext.Session.SetString("persoonID", checklogin.persoonID.ToString());
                string accountID = HttpContext.Session.GetString("accountID");


                if (!string.IsNullOrEmpty(accountID))
                {
                    ViewData["ingelogd"] = "1";
                }
                if (Int32.TryParse(accountID, out int accountIDInt))
                {
                    var beheerder = loginRepository.BeheerderCheck(accountIDInt);
                    if (beheerder == true)
                    {
                        HttpContext.Session.SetString("beheerder", "1");
                    }
                    else 
                    {
                        HttpContext.Session.SetString("beheerder", "-1");
                        HttpContext.Session.SetString("gebruiker", "1");
                    }
                }
                return Redirect("/homelogin");
            }
        }
    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/signuppage.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizWebsite.Pages
{
    public class signuppageModel : PageModel
    {
        public bool Invalidlogin { get; private set; }
        public IEnumerable<Account> accounts
        {
            get { return loginRepository.GetAlleAccounts(); }
        }

        public List<Account> account { get { return loginRepository.GetAlleAccounts(); } }

        public IActionResult OnPostSubmit([FromForm] string voornaam, string achternaam, string gebruikersnaam, string wachtwoord, string email, int klas)
        {
            if (ModelState.IsValid)
            {
                var addedAccount = loginRepository.AddPersoon(voornaam, achternaam, gebruikersnaam, wachtwoord, email, klas);
                return Redirect("/loginpage");
            }
            else
            {
                Invalidlogin = true;
                return Page();
            }
        }
    }
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Cijfer.cshtml
@page
@model QuizWebsite.Pages.CijferModel
@{
}
<div class="jumbotron text-lg-center">
    <h1>Jouw Cijfer @Model.cijfer Van (quiz)</h1>
    <p>Bedankt Voor Het Maken Van De Quiz</p>
</div>

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Index1.cshtml
@page
@model QuizWebsite.Pages.Index1Model
@{
}

QuizWebsite/QuizWebsite/QuizWebsite/Pages/QuizJoinen.cshtml
@page
@model QuizWebsite.Pages.QuizJoinenModel
@{
}

<div class="jumbotron text-lg-center">
    <h1>Hier Kunt U Quiz De Maken</h1>
</div>
<div>
    <form method="post">
        <table class="table">
            <tr>
                <td>
                    <input type="text" name="quizID" />
                </td>
                <td><input type="submit" name="subBtn" id="subBtn" asp-page-handler="JoinQuiz"/></td>
            </tr>
        </table>
    </form>
</div>

QuizWebsite/QuizWebsite/QuizWebsite/Pages/QuizUpdaten.cshtml
@page
@model QuizWebsite.Pages.QuizUpdatenModel
@{
}
<div class="jumbotron text-lg-center">
    <h1>Update Uw Quiz Hier!</h1>
    <p>Welke Quiz Wilt U Update?</p>
</div>
<div>
    <form method="post">
        <table class="table">
            <tr>
                <td>
                    <input type="text" name="quizID" />
                </td>
                <td><input type="submit" name="subBtn" id="subBtn" asp-page-handler="KiesQuiz" /></td>
            </tr>
        </table>
        <table class="table">
            <tr>
                @foreach (var item in Model.quizes)
                {
                    <td>@item.naam : @item.quizID</td>
                }
            </tr>

        </table>
    </form>
</div>

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Quizmaken.cshtml
@page
@model QuizWebsite.Pages.QuizmakenModel
@{
}
<div class="jumbotron text-lg-center">
    <h1>Quiz Aanmaken</h1>
    <p>Hier kan u een nieuwe quiz maken.</p>
</div>
<form method="post">
    <table class="table-borderless">
        <tr>

            <th scope="col">Quiznaam</th>
        </tr>
        <tr>
            <td><input type="text" name="naam"/></td>
        </tr>
        @*<tr>
            <th scope="col">Categorie</th>
        </tr>
        <tr>
            <td>
                <select name="categorie">
                    <option>School</option>
                    <option>Landen</option>
                    <option>Economie</option>
                    <option>Engels</option>
                </select>
                <label for="categorie">Kies een Categorie</label>
            </td>
        </tr>*@

        <tr>
            <td><button class="btn-secondary" asp-page-handler="QuizAanmaken">Quiz Aanmaken</button></td>
        </tr>
    </table>
</form>

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Resultaten.cshtml
@page
@model QuizWebsite.Pages.ResultatenModel
@{
}
<div class="jumbotron text-center">
    <h3>Hier Zijn Jouw Resultaten!</h3>
</div>
<div>
<table class="table">
    @foreach (var item in Model.Quizresultaten)
    {
    <tr>
        <td>@item.naam</td>
        <td>@item.cijfer</td>
    </tr>
    }
</table>
</div>

QuizWebsite/QuizWebsite/QuizWebsite/Pages/VraagBeantwoorden.cshtml
@page
@model QuizWebsite.Pages.VraagBeantwoordenModel
@{
//"{quizID}"
}

<div class="jumbotron text-lg-center">
    <h1>Vragen Toevoegen aan (@Model.quizID)</h1>
    <p>Hier kunt u vragen toevoegen aan uw quiz!</p>
</div>
<div class="container-fluid">
    <div class="col-md-12">
        <form method="post">
            @{
                int i = 0;
                int huidigevraag = -1;
                if (Model.vragenmetantwoord != null)
                {
                    while (i < Model.vragenmetantwoord.Count)
                    {

                        // dit gebeurt maar 1x: alleen bij de eerste keer; we weten dan dat we records hebben en kunnen veilig het vraagID opvragen en bewaren
                        if (huidigevraag == -1) { huidigevraag = Model.vragenmetantwoord[i].vraagID; }

                        // we zijn bij een nieuwe vraag (per definitie van de lus)

                        <table class="table">
                            <caption style="caption-side: top !important; color: black !important; font-size: 20px !important; font-weight: bold !important;">@Model.vragenmetantwoord[i].vraag</caption>
                            <thead>
                                <tr>
                                    <th colspan="2">Antwoord</th>
                                    <th colspan="2">Kruis Aan</th>
                                    <td><input type="hidden" name="vraagID" value="@huidigevraag" /></td>
                                </tr>
                            </thead>
                            <tbody>

                                @* deze WHILE lus laat alleen antwoorden zien bij de huidige vraag*@
                                @while (i < Model.vragenmetantwoord.Count && Model.vragenmetantwoord[i].vraagID == huidigevraag)
                                {

                                    // sla het huidige record even op ; handig voor als we meer informatie uit het record nodig hebben in de HTML
                                    QRYQuizVragen record = Model.vragenmetantwoord[i];
                                    @if (record.antwoord != null)
                                    {
                                        // laat de info uit het record zien
                                        <tr>
                                            <td colspan="2">@record.antwoord</td>
                                            <td colspan="2"><input type="checkbox" name="antwoordID" value="@record.antwoordID" /></td>
                                        </tr>

                                    }

                                    // ga naar het volgende record; mogelijk komen we bij een nieuwe vraag aan
                                    i++;

                                }
                            </tbody>
                        </table>

                        // we zijn bij een nieuwe vraag, mits we niet voorbij het einde van de lijst zijn. dus even checken of i>lengte lijst.
                        if (i < Model.vragenmetantwoord.Count)
                        {
                            huidigevraag = Model.vragenmetantwoord[i].vraagID;

                        }

                    }
                    <tr>
                        <td>
                            <button asp-route-quizID="@Model.quizID" asp-route-accountID="@Model.accountID" asp-page-handler="QuizInleveren">Quiz Inleveren</button>
                        </td>

                    </tr>
                }
            }
        </form>
    </div>
</div>

QuizWebsite/QuizWebsite/QuizWebsite/Pages/Vraagaanmaken.cshtml
@page
@model QuizWebsite.Pages.VraagaanmakenModel
@{
}

<style>
</style>

<div class="jumbotron text-lg-center">
    <h1>Vragen Toevoegen aan (Quiznaam)</h1>
    <p>Hier kunt u vragen toevoegen aan uw quiz!</p>
</div>
<div class="container-fluid">
    <div class="col-md-12">
        @{
            int i = 0;
            int huidigevraag = -1;
            if (Model.vragenmetantwoord != null)
            {
                while (i < Model.vragenmetantwoord.Count)
                {

                    // dit gebeurt maar 1x: alleen bij de eerste keer; we weten dan dat we records hebben en kunnen veilig het vraagID opvragen en bewaren
                    if (huidigevraag == -1) { huidigevraag = Model.vragenmetantwoord[i].vraagID; }

                    // we zijn bij een nieuwe vraag (per definitie van de lus)
                <form method="post">
                    <table class="table">
                        <caption>@Model.vragenmetantwoord[i].vraag</caption>
                        <thead>
                            <tr>
                                <th>Nr</th>
                                <th>Antwoord</th>
                                <th>Kruis Aan</th>
                                <th><button asp-route-vraagID="@huidigevraag" asp-route-quizIDInt="@Model.quizIDInt" asp-page-handler="VraagVerwijderen">Vraag Verwijderen</button></th>
                            </tr>
                            <tr>
                                <th><input type="text" name="antwoord"></th>
                                <th><input type="hidden" asp-for="@huidigevraag"><button asp-route-quizIDInt="@Model.quizIDInt" asp-page-handler="AntwoordToevoegen">+</button></th>
                            </tr>


                        </thead>
                                <tbody>

                                    @* deze WHILE lus laat alleen antwoorden zien bij de huidige vraag*@
                                    @while (i < Model.vragenmetantwoord.Count && Model.vragenmetantwoord[i].vraagID == huidigevraag)
                                    {
                                        // sla het huidige record even op ; handig voor als we meer informatie uit het record nodig hebben in de HTML
                                        QRYQuizVragen record = Model.vragenmetantwoord[i];
                                        @if (record.antwoord != null)
                                        {
                                            // laat de info uit het record zien
                                    <tr>
                                        <td>@record.vraagID</td>
                                        <td>@record.antwoord</td>
                                        <td>@record.antwoordID</td>
                                        @if (record.goed)
                                        {
                                            <td><input type="checkbox" name="ischecked" value="@record.antwoordID" checked/></td>
                                        }
                                        else
                                        {
                                            <td><input type="checkbox" name="ischecked" value="@record.antwoordID"/></td>
                                        }
                                        <td><button asp-route-antwoordID="@record.antwoordID" asp-route-quizIDInt="@Model.quizIDInt" asp-page-handler="UpdateAntwoord">Update</button></td>
                                        <td><button asp-route-antwoordID="@record.antwoordID" asp-route-quizIDInt="@Model.quizIDInt" asp-page-handler="AntwoordVerwijderen">Verwijder</button></td>
                                    </tr>
                                        }
                                        // ga naar het volgende record; mogelijk komen we bij een nieuwe vraag aan
                                        i++;

                                    }
                                </tbody>
                            </table>
                </form>
                        // we zijn bij een nieuwe vraag, mits we niet voorbij het einde van de lijst zijn. dus even checken of i>lengte lijst.
                        if (i < Model.vragenmetantwoord.Count)
                        {
                            huidigevraag = Model.vragenmetantwoord[i].vraagID;

                        }

                    }
                }
            }
    </div>
    </div>
<div class="container-fluid">
    <div class="col-md-12">
        <form method="post">
            <table>
                <thead>
                    <tr>
                        <th>Vraag</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><input type="text" name="vraag"></td>
                        <td><input type="hidden" asp-for="quizIDInt"><button asp-page-handler="VraagAanmaken">+</button></td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
    @*</div>
        <form method="post">
            <table class="table-borderless">

                <tr>
                    <th scope="col">Vraag</th>
                </tr>
                <tr>
                    <td><input type="text" name="vraag" /></td>
                </tr>
                <tr>
                    <th scope="col">Antwoorden</th>
                </tr>
                <tr>
                    <td><input type="text" naam="antwoord" /></td>
                </tr>
                <tr>
                    <td><button class="btn-secondary" type="submit" name="quizAanmaken">Vraag toevoegen</button></td>
                </tr>
            </table>
        </form>*@

QuizWebsite/QuizWebsite/QuizWebsite/Pages/homelogin.cshtml
@page
@model QuizWebsite.Pages.homeloginModel
@{
    ViewData["Title"] = "Home pagina";
}
    <div class="jumbotron text-center">
        <h3>Welkom @Model.account.gebruikersnaam op de website!</h3>
    </div>

QuizWebsite/QuizWebsite/QuizWebsite/Pages/loginpage.cshtml
@page
@model QuizWebsite.Pages.loginpageModel
@{
    ViewData["Title"] = "Inloggen";
}
<body>
    <div class="loginbox">
        <div class="jumbotron text-center">
            <h1>Inloggen account</h1>
        </div>

        <form method="post">
            @if (Model.Invalidlogin)
            {
                <p class="alert-info">Foutmelding: Ongeldige inlog</p>
            }
            <p></p>
            <p>Gebruikersnaam</p>
            <input type="text" name="gebruikersnaam" placeholder="Gebruikersnaam" required />
            <p></p>
            <p>Wachtwoord</p>
            <input type="password" name="wachtwoord" placeholder="Wachtwoord" required />
            <p></p>
            <input type="submit" name="" asp-page-handler="Checklogin" value="Inloggen" />
            <p></p>
            <a class="nav-link text-dark" asp-area="" asp-page="/signuppage">Heeft u nog geen account? Maak deze hier aan!</a>
        </form>
    </div>
</body>